// Shared constants used across the application

export const EventType = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  LOGIN_FAILED: 'LOGIN_FAILED',
  TOKEN_REFRESH: 'TOKEN_REFRESH',
  DOCUMENT_OPEN: 'DOCUMENT_OPEN',
  DOCUMENT_VIEW: 'DOCUMENT_VIEW',
  PAGE_VIEW: 'PAGE_VIEW',
  PAGE_REQUEST: 'PAGE_REQUEST',
  SESSION_START: 'SESSION_START',
  SESSION_END: 'SESSION_END',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  TOKEN_REQUEST: 'TOKEN_REQUEST',
  TOKEN_FAILURE: 'TOKEN_FAILURE',
  DIRECT_PDF_REQUEST: 'DIRECT_PDF_REQUEST',
  DOWNLOAD_ATTEMPT: 'DOWNLOAD_ATTEMPT',
  MULTIPLE_SESSION: 'MULTIPLE_SESSION',
  RAPID_PAGE_ACCESS: 'RAPID_PAGE_ACCESS',
  SUSPICIOUS_API_REQUEST: 'SUSPICIOUS_API_REQUEST',
  UNAUTHORIZED_ACCESS_ATTEMPT: 'UNAUTHORIZED_ACCESS_ATTEMPT',
  USER_BLOCKED: 'USER_BLOCKED',
  USER_UNBLOCKED: 'USER_UNBLOCKED',
  DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
  DOCUMENT_DELETED: 'DOCUMENT_DELETED',
  PERMISSION_GRANTED: 'PERMISSION_GRANTED',
  PERMISSION_REVOKED: 'PERMISSION_REVOKED',
};

export const RiskLevel = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  CRITICAL: 'critical',
};

export const SecurityAction = {
  ALLOW: 'ALLOW',
  MONITOR: 'MONITOR',
  RATE_LIMIT: 'RATE_LIMIT',
  REQUIRE_REAUTH: 'REQUIRE_REAUTH',
  BLOCK_SESSION: 'BLOCK_SESSION',
  BLOCK_USER: 'BLOCK_USER',
};
